{
  "hash": "c356aab3f914782cf2740dc791407c47",
  "result": {
    "markdown": "---\ntitle: \"Black-Throated Blue Warblers linear model selection\"\ndescription: |\n Model Selection and Justification of Black-throated Blue Warbler capture histories, Hubbard Brook Experimental Forest, 1986 - 2010  .\nauthor:\n  - name: Elmera Azadpour\n    url: {}\ndate: 2021-09-18\nformat: html\ncategories: [code, analysis, linear model]\n---\n\n\n### To access data, html and Rmd files:\n\n-   https://github.com/elmeraa/elmera-azadpour-206-final\n-   you will find the warblers data in the \"exam_data\" folder\n-   you will find the Rmd and html files in the \"task_code\" folder\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(broom)\nlibrary(car)\nlibrary(GGally)\nlibrary(stargazer)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Read in bt_warblers.csv\nwarblers <- read_csv(here(\"posts\", \"2021-09-18-black-throated-blue-warblers-visualization\",\"bt_warblers.csv\"))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 1555 Columns: 8\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): sex, elevation, age_banded\ndbl (5): bill_depth, bill_culmen, mass, tarsus1, wing_r\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n:::\n\n\n## Data exploration and visualization\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-2-3.png){width=672}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n## Model 1: DV is bird mass, predictor variables are: right wing length (mm), tarsus length (mm), age of bird at capture, and sex. \nwarblers_lm <- lm(mass ~ wing_r + tarsus1 + age_banded + sex, data = warblers_clean)\nsummary(warblers_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mass ~ wing_r + tarsus1 + age_banded + sex, data = warblers_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.8621 -0.3485 -0.0150  0.3692  4.9237 \n\nCoefficients:\n               Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    4.613330   1.118242   4.126 4.17e-05 ***\nwing_r         0.073854   0.015641   4.722 2.86e-06 ***\ntarsus1        0.074342   0.033644   2.210   0.0275 *  \nage_bandedASY -0.005195   0.138458  -0.038   0.9701    \nage_bandedSY   0.016213   0.135266   0.120   0.9046    \nsexM          -1.042929   0.072653 -14.355  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5926 on 661 degrees of freedom\nMultiple R-squared:  0.3208,\tAdjusted R-squared:  0.3157 \nF-statistic: 62.44 on 5 and 661 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(warblers_lm) # 1202.795\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1202.795\n```\n:::\n\n```{.r .cell-code}\nvif(warblers_lm) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               GVIF Df GVIF^(1/(2*Df))\nwing_r     2.344573  1        1.531200\ntarsus1    1.041942  1        1.020755\nage_banded 1.141061  2        1.033540\nsex        2.505606  1        1.582911\n```\n:::\n\n```{.r .cell-code}\nwarblers_lm \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mass ~ wing_r + tarsus1 + age_banded + sex, data = warblers_clean)\n\nCoefficients:\n  (Intercept)         wing_r        tarsus1  age_bandedASY   age_bandedSY  \n     4.613330       0.073854       0.074342      -0.005195       0.016213  \n         sexM  \n    -1.042929  \n```\n:::\n\n```{.r .cell-code}\nwarblers_lm_tidy <- tidy(warblers_lm)\nwarblers_lm_tidy\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 6 × 5\n  term          estimate std.error statistic  p.value\n  <chr>            <dbl>     <dbl>     <dbl>    <dbl>\n1 (Intercept)    4.61       1.12      4.13   4.17e- 5\n2 wing_r         0.0739     0.0156    4.72   2.86e- 6\n3 tarsus1        0.0743     0.0336    2.21   2.75e- 2\n4 age_bandedASY -0.00520    0.138    -0.0375 9.70e- 1\n5 age_bandedSY   0.0162     0.135     0.120  9.05e- 1\n6 sexM          -1.04       0.0727  -14.4    7.12e-41\n```\n:::\n\n```{.r .cell-code}\nwarblers_lm_fit <- glance(warblers_lm)\nwarblers_lm_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squa…¹ sigma stati…²  p.value    df logLik   AIC   BIC devia…³\n      <dbl>        <dbl> <dbl>   <dbl>    <dbl> <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1     0.321        0.316 0.593    62.4 2.49e-53     5  -594. 1203. 1234.    232.\n# … with 2 more variables: df.residual <int>, nobs <int>, and abbreviated\n#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance\n# ℹ Use `colnames()` to see all variable names\n```\n:::\n\n```{.r .cell-code}\nplot(warblers_lm)\n```\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-4.png){width=672}\n:::\n\n```{.r .cell-code}\n## Model 2: DV is bird mass, predictor variables are:  tarsus length (mm), age of bird at capture, and sex. \nwarblers_lm2 <- lm(mass ~  tarsus1 + age_banded + sex, data = warblers_clean)\nsummary(warblers_lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mass ~ tarsus1 + age_banded + sex, data = warblers_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.8935 -0.3683 -0.0179  0.3687  4.8730 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    8.95060    0.64792  13.814   <2e-16 ***\ntarsus1        0.08051    0.03416   2.357   0.0187 *  \nage_bandedASY  0.01871    0.14057   0.133   0.8942    \nage_bandedSY  -0.02246    0.13717  -0.164   0.8700    \nsexM          -0.78737    0.04924 -15.990   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.602 on 662 degrees of freedom\nMultiple R-squared:  0.2979,\tAdjusted R-squared:  0.2937 \nF-statistic: 70.22 on 4 and 662 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(warblers_lm2) # 1222.922\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1222.922\n```\n:::\n\n```{.r .cell-code}\nvif(warblers_lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               GVIF Df GVIF^(1/(2*Df))\ntarsus1    1.040369  1        1.019985\nage_banded 1.076407  2        1.018578\nsex        1.115105  1        1.055985\n```\n:::\n\n```{.r .cell-code}\nplot(warblers_lm2)\n```\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-5.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-6.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-7.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-8.png){width=672}\n:::\n\n```{.r .cell-code}\nwarblers_lm_fit2 <- glance(warblers_lm2)\n\n## Model 3: DV is bird mass, predictor variables are: age of bird at capture, and sex. \nwarblers_lm3 <- lm(mass ~ age_banded + sex, data = warblers_clean)\nsummary(warblers_lm3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = mass ~ age_banded + sex, data = warblers_clean)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-1.9179 -0.3566 -0.0179  0.3476  4.8476 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   10.44619    0.13183  79.242   <2e-16 ***\nage_bandedASY  0.01038    0.14101   0.074    0.941    \nage_bandedSY  -0.02827    0.13762  -0.205    0.837    \nsexM          -0.76550    0.04853 -15.775   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.6041 on 663 degrees of freedom\nMultiple R-squared:  0.292,\tAdjusted R-squared:  0.2888 \nF-statistic: 91.15 on 3 and 663 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nAIC(warblers_lm3) # 1226.497\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1226.497\n```\n:::\n\n```{.r .cell-code}\nvif(warblers_lm3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               GVIF Df GVIF^(1/(2*Df))\nage_banded 1.075537  2        1.018372\nsex        1.075537  1        1.037081\n```\n:::\n\n```{.r .cell-code}\nplot(warblers_lm3)\n```\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-9.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-10.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-11.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-12.png){width=672}\n:::\n\n```{.r .cell-code}\nwarblers_lm_fit3 <- glance(warblers_lm3)\n\n# Histograms\nggplot(data = warblers_clean, aes(x = mass)) +\n  geom_histogram(bins = 15) +\n  facet_wrap(~sex, scales = \"free\")\n```\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-13.png){width=672}\n:::\n\n```{.r .cell-code}\n# QQ Plots\nggplot(data= warblers_clean, aes(sample = mass)) +\n  geom_qq() +\n  facet_wrap(~sex)\n```\n\n::: {.cell-output-display}\n![](black-throated-blue-warblers-visualization_files/figure-html/unnamed-chunk-3-14.png){width=672}\n:::\n:::\n\n\n### Regression table\n\n\n\n```{.r .cell-code}\nstargazer(warblers_lm, type = \"html\")\n```\n\n\n<table style=\"text-align:center\"><tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"></td><td><em>Dependent variable:</em></td></tr>\n<tr><td></td><td colspan=\"1\" style=\"border-bottom: 1px solid black\"></td></tr>\n<tr><td style=\"text-align:left\"></td><td>mass</td></tr>\n<tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">wing_r</td><td>0.074<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.016)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">tarsus1</td><td>0.074<sup>**</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.034)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">age_bandedASY</td><td>-0.005</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.138)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">age_bandedSY</td><td>0.016</td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.135)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">sexM</td><td>-1.043<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(0.073)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td style=\"text-align:left\">Constant</td><td>4.613<sup>***</sup></td></tr>\n<tr><td style=\"text-align:left\"></td><td>(1.118)</td></tr>\n<tr><td style=\"text-align:left\"></td><td></td></tr>\n<tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\">Observations</td><td>667</td></tr>\n<tr><td style=\"text-align:left\">R<sup>2</sup></td><td>0.321</td></tr>\n<tr><td style=\"text-align:left\">Adjusted R<sup>2</sup></td><td>0.316</td></tr>\n<tr><td style=\"text-align:left\">Residual Std. Error</td><td>0.593 (df = 661)</td></tr>\n<tr><td style=\"text-align:left\">F Statistic</td><td>62.442<sup>***</sup> (df = 5; 661)</td></tr>\n<tr><td colspan=\"2\" style=\"border-bottom: 1px solid black\"></td></tr><tr><td style=\"text-align:left\"><em>Note:</em></td><td style=\"text-align:right\"><sup>*</sup>p<0.1; <sup>**</sup>p<0.05; <sup>***</sup>p<0.01</td></tr>\n</table>\n\n\n### Model Selection and Justification\n\n**Model 1:** DV is bird mass, predictor variables are: right wing length (mm), tarsus length (mm), age of bird at capture, and sex. (I have selected this one as the final model). *Model 2:* DV is bird mass, predictor variables are: tarsus length (mm), age of bird at capture, and sex. *Model 3:* DV is bird mass, predictor variables are: age of bird at capture, and sex.\n\n-   Warblers data set is normally distributed for mass with respect to sex.\n\n-   When looking at the Residual Variances, for Homoscedasticity, it appears residuals appear more randomly distributed evenly around the horizontal dotted line compared to model 2 and model 3.\n\n-   Residual plots and Q-Q plots visually show that model 1 meets the homoscedasticity and normality assumptions of linear regression.\n\n-   AIC score for model 1 was the lowest (1202.8) compared to model 2 (1222.92) and 3 (1226.5).\n\n-   Conceptually, including predictor variables like wing length, tarsus length, age of bird capture and sex indicate a stronger correlation to bird mass (0.32). The adjusted R^2^ value here (0.32) indicates that 32 % of variance in body mass is explained by these variables included in the model.\n\n#### Interpreting given coeffients in Model 1:\n\n-   The slope of the linear model was 0.0739 for right wing length (mm), 0.0743 for tarsus length (mm), -0.052 for age of bird at capture, -1.043 for sex, and the y-intercept was 4.613. This suggests that on average, we expect that bird body mass (g) to increase by 0.0739 grams for each 1 mm of increase in right wing length. We expect bird body mass to increase by 0.0743 grams for each 1 mm of increase in bird tarsus length.\n\n#### Black-throated blue warbler data source:\n\n-   Rodenhouse, N., R. Holmes, S. Sillett, and M. Webster. 2019. Black-throated Blue Warbler capture histories, Hubbard Brook Experimental Forest, 1986 - 2010 ver 4. Environmental Data Initiative. https://doi.org/10.6073/pasta/ea985022acfdb76cd7beeaf8da6c39b1\n",
    "supporting": [
      "black-throated-blue-warblers-visualization_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}