{
  "hash": "251a5357f7ab829ea80c118c5d7a10a3",
  "result": {
    "markdown": "---\ntitle: \"Two Sample T-Test\"\ndescription: |\n  Regression, two sample t-test, and chi-square analysis of two species of sea turtles in Shark Bay, Australia .\nauthor:\n  - name: Elmera Azadpour\ndate: 2021-03-31\nformat: html\ncategories: [code, analysis, t-test]\nimage: \"chi-square.jpg\"\n---\n\n\n## Load Packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(broom)\nlibrary(effsize)\nlibrary(janitor)\nlibrary(kableExtra)\n```\n:::\n\n\n### To access data, html and Rmd/qmd files:\n\n-   the sharkbay sea turtles data can be found in the *exam_data* folder of [this repo]( https://github.com/elmeraa/elmera-azadpour-206-final); the Rmd and html files, denoted as *azadpour_turtles*, can be found in the *task_code* folder\n-   the qmd format can be found [here](https://github.com/elmeraa/elmeraa.github.io/tree/main/posts/2021-03-31-two-sample-t-test) \n\n## Read in sea turtles data (source: Environmental Data Initiative)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsea_turtles <- read_csv(here(\"posts\", \"2021-03-31-two-sample-t-test\", \"sharkbay_sea_turtles.csv\")) \nsea_turtles_clean <- sea_turtles %>% \n  dplyr::select(species, length, width, burr)\n```\n:::\n\n\n## Exploratory visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(sea_turtles_clean, aes(x = length,\n                              y= width)) +\n  geom_point() +\n  theme_minimal()+\n  labs(x =\"Curved carapace length at midline (cm)\", \n  y = \"Curved carapace width at widest point (cm)\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing missing values (geom_point).\n```\n:::\n\n::: {.cell-output-display}\n![](two-sample-t-test_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## Linear Regression\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## linear regression \nturtles_lm <- lm(length ~ width, data = sea_turtles_clean)\n\n# Return the complete overview:\nsummary(turtles_lm)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = length ~ width, data = sea_turtles_clean)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-10.1332  -2.6294   0.0433   2.4164  19.6729 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.16968    1.50479  -0.113     0.91    \nwidth        1.08061    0.01749  61.775   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 3.802 on 280 degrees of freedom\n  (1 observation deleted due to missingness)\nMultiple R-squared:  0.9316,\tAdjusted R-squared:  0.9314 \nF-statistic:  3816 on 1 and 280 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\n# We can use the broom::tidy() function to get the model outputs in nice data frame format:\nturtles_lm_tidy <- broom::tidy(turtles_lm)\n\n# Get the intercept: \nturtles_int <- turtles_lm_tidy$estimate[1]\nturtles_int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.1696804\n```\n:::\n\n```{.r .cell-code}\n# Then to get the flipper_length coefficient:\nturtles_coef <- turtles_lm_tidy$estimate[2]\nturtles_coef\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.080611\n```\n:::\n\n```{.r .cell-code}\n#What about getting some other model information (degrees of freedom, F-statistic, p-value, etc.)?\n#Many of these statistical outcomes can be accessed more easily using broom::glance().\n# Metrics at a glance: \nturtles_lm_out <- broom::glance(turtles_lm)\nturtles_lm_out\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 1 × 12\n  r.squared adj.r.squ…¹ sigma stati…²   p.value    df logLik   AIC   BIC devia…³\n      <dbl>       <dbl> <dbl>   <dbl>     <dbl> <dbl>  <dbl> <dbl> <dbl>   <dbl>\n1     0.932       0.931  3.80   3816. 3.66e-165     1  -776. 1558. 1568.   4048.\n# … with 2 more variables: df.residual <int>, nobs <int>, and abbreviated\n#   variable names ¹​adj.r.squared, ²​statistic, ³​deviance\n# ℹ Use `colnames()` to see all variable names\n```\n:::\n\n```{.r .cell-code}\n# Explore model assumptions\nplot(turtles_lm)\n```\n\n::: {.cell-output-display}\n![](two-sample-t-test_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](two-sample-t-test_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](two-sample-t-test_files/figure-html/unnamed-chunk-3-3.png){width=672}\n:::\n\n::: {.cell-output-display}\n![](two-sample-t-test_files/figure-html/unnamed-chunk-3-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# Pearson’s r\nturtles_cor <- cor.test(sea_turtles_clean$length, sea_turtles_clean$width)\nturtles_cor\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  sea_turtles_clean$length and sea_turtles_clean$width\nt = 61.775, df = 280, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.9562175 0.9723919\nsample estimates:\n      cor \n0.9652165 \n```\n:::\n:::\n\n\n### Regression summary of sea turtle curved carapace length and width at midline (cm).\n\n-   Simple linear regression was used to explore the relationship between sea turtles curved carapace length at midline (cm) and curved carapace width at widest point (cm) across two sea turtle species: green or loggerhead. A significant regression model was found ($\\beta$ = 1.081, F(1,280) = 3816.1, p \\< 0.001) with an R^2^ of 0.932.\n\n### Comparing carapace lengths between green and loggerhead turtles\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Lets just look at the raw data \n#ggplot(data = sea_turtles_clean, aes(x = species, y = length)) + geom_boxplot(aes(col=species))\n# not very different.. \n\n# Histograms\nggplot(data = sea_turtles_clean, aes(x = length)) +\n  geom_histogram(bins = 15) +\n  facet_wrap(~species, scales = \"free\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing non-finite values (stat_bin).\n```\n:::\n\n::: {.cell-output-display}\n![](two-sample-t-test_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# QQ Plots\nggplot(data= sea_turtles_clean, aes(sample = length)) +\n  geom_qq() +\n  facet_wrap(~species)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 1 rows containing non-finite values (stat_qq).\n```\n:::\n\n::: {.cell-output-display}\n![](two-sample-t-test_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\n## Two sample t-test\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# two sample t-test\nturtle_length_green <- sea_turtles_clean %>% \n  dplyr::select(c(\"length\", \"species\")) %>% \n  filter(species == \"green\") %>% \n  pull(length)\n\nturtle_length_loggerhead<- sea_turtles_clean %>% \n  dplyr::select(c(\"length\", \"species\")) %>% \n  filter(species == \"loggerhead\") %>% \n  pull(length)\n\nttest <-t.test(turtle_length_green, turtle_length_loggerhead)\nttest_tidy <- tidy(ttest)\n\n#turtles_clean_table <- sea_turtles_clean %>% \n#group_by(species) %>% \n  #summarise(mean_length = mean(length, na.rm=T),\n            #sd_length = sd(length, na.rm=T),\n            #n = n())\n\n# cohens d/ effect size\ncohen_test <- cohen.d(turtle_length_green, turtle_length_loggerhead, na.rm = TRUE)\n```\n:::\n\n\n### Two sample t-test conclusions:\n\n-   I used a two-sample t-test because I wanted to compare differences between 2 groups (turtle species) and compare means (continuous data) of curved carapace lengths.\n-   This analysis indicates green sea turtles had a larger mean (92.64 ± 15.78, *n* = 188; mean ± 1 standard deviation), compares to loggerhead sea turtles which had a smaller mean (89.92 ± 11.44, *n* = 95; mean ± 1 standard deviation). The actual difference in means from green and loggerhead sea turtles is 2.72. The outcome of the two sample t-test indicated that there is somewhat strong chance of (*p* \\> 0.001) of randomly selecting two samples from populations with the same that are this difference by change. In sum, the difference in means is significant (Welch's two-sample t-test: t(244.17) = 1.65, *p*-value = 9.98e-02) and the effect size is negligible (Cohen's *d* = 0.19).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Finalized table that shows counts and proportions of presence of burrowing barnacles to sea turtle species\"\nsea_turtles_burr <- sea_turtles_clean %>%  \n  dplyr::select(species, burr)\n\nburr_counts <- sea_turtles_burr %>% \n  janitor::tabyl(species, burr)\n\nburr_proportions <- burr_counts %>% \n  adorn_percentages() %>% \n  janitor::adorn_pct_formatting(digits = 2) %>% \n  adorn_ns() %>% \n  drop_na()\n\nburr_ct <- burr_proportions %>% \n  column_to_rownames(var = \"species\")\n\nburr_ct %>%  \n  kable(col.names = c(\"No\",\n                      \"Yes\"),\n    caption = \"**Table 1**: Association between sea turtle species and presence of burrowing barnacles\") %>% \n  kable_styling(full_width = FALSE)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<table class=\"table\" style=\"width: auto !important; margin-left: auto; margin-right: auto;\">\n<caption>**Table 1**: Association between sea turtle species and presence of burrowing barnacles</caption>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\">   </th>\n   <th style=\"text-align:left;\"> No </th>\n   <th style=\"text-align:left;\"> Yes </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> green </td>\n   <td style=\"text-align:left;\"> 87.23% (164) </td>\n   <td style=\"text-align:left;\"> 12.77% (24) </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> loggerhead </td>\n   <td style=\"text-align:left;\"> 69.47%  (66) </td>\n   <td style=\"text-align:left;\"> 30.53% (29) </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Chi-square test for independence\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Chi-square test\nburr_ct <- burr_counts %>%   \n  drop_na() %>% \n  column_to_rownames(var = \"species\")\n  \nsurvey_x2 <- chisq.test(burr_ct)\nsurvey_x2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test with Yates' continuity correction\n\ndata:  burr_ct\nX-squared = 11.938, df = 1, p-value = 0.00055\n```\n:::\n\n```{.r .cell-code}\nsurvey_tidy <- tidy(survey_x2)\n```\n:::\n\n\n### Chi-square results and summary\n\nA chi-square test for independence compares two variables in a contingency table to see if they are related. In a more general sense, it tests to see whether distributions of categorical variables differ from each another. For this analysis, there is a significant association (i.e. non-independence) between sea turtle species and and the presence of burrowing barnacles ($\\chi$^2^(1) = 11.94, *p*-value = 5.5e-04).\n\n### Sea turtle data source:\n\n-   Heithaus, M. and J. Thomson. 2019. Marine turtles captured during haphazard at-sea surveys in Shark Bay, Australia from February 2008 to December 2013 ver 4. Environmental Data Initiative. https://doi.org/10.6073/pasta/7696e20214fbf84f25d664ff7dc8050c\n",
    "supporting": [
      "two-sample-t-test_files/figure-html"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}